import Head from 'next/head'
import Image from 'next/image'
import Advert from '../components/advert'
import styles from '../styles/index.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Notflix - Watch Nothing Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles["notflix-sans-font-loaded"]}>
          <div className={styles.container} dir="ltr">
            {Advert()}
          </div>
        
        <section>
          <h1>Unlimited moves, TV shows, and more.</h1>
          <h2>Watch anywhere. Cancel anytime.</h2>
          <h2>Ready to watch? Enter your email to create or restart your membership.</h2>
          <input></input>
          <button>Get started</button>
        </section>

        <section className={styles.enjoy}>
          <h1 className={styles['our-story-card-title']}>Enjoy on your TV.</h1>
          <h3>Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.</h3>
          <div className={styles.tv}></div>
        </section>

        <h1 className={styles.title}>Sign In</h1>
        <input></input>
        <input></input>
        <button>Sign In</button>
        <a href="">Need help?</a>
        
        <p className={styles.description}>New to Notflix? <a href="">Sign up now.</a>
        </p>

        <p>This page is protected by literally nothing, please be nice <a href="">Learn nothing.</a></p>
        </div>
        

      
      <header>NOTFLIX</header>
    </>
  )
}
