import Head from 'next/head'
import Image from 'next/image'
import Advert from '../components/advert'
import styles from '../styles/index.module.css'
import Topheader from '../components/topheader'
import MainCard from '../components/maincard'
import tv from '../components/tv'


export default function Home() {
  return (
    <>
      <Head>
        <title>Notflix - Watch Nothing Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles["notflix-sans-font-loaded"]}>
          <div className={styles.container} dir="ltr">
            {Advert()}
            {Topheader()}
            {MainCard()}
            {tv()}
          </div>


        <h1 className={styles.title}>Sign In</h1>
        <input></input>
        <input></input>
        <button>Sign In</button>
        <a href="">Need help?</a>
        
        <p className={styles.description}>New to Notflix? <a href="">Sign up now.</a>
        </p>

        <p>This page is protected by literally nothing, please be nice <a href="">Learn nothing.</a></p>
        </div>
        

      
      <header>NOTFLIX</header>
    </>
  )
}
