import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header id='main-header'>NOTFLIX</header>

      <main className={styles.main}>
        <h1 className={styles.title}>Sign In</h1>
        <input></input>
        <input></input>
        <button>Sign In</button>
        <a href="">Need help?</a>
        
        <p className={styles.description}>New to Notflix? <a href="">Sign up now.</a>
        </p>

        <p>This page is protected by literally no one, please be nice <a href="">Learn nothing.</a></p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}